entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"

log:
  level: DEBUG

api:
  dashboard: true

global:
  sendAnonymousUsage: false

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml

certificatesResolvers:
  letsencrypt:
    acme:
      email: yourmail@example.com #### Change Here
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
